name: birdwatch

services:
  analyzer:
    build: ./analyzer
    volumes:
      # 解析結果はHDDに保存
      - /volume2/docker2/birdwatch/data:/data
      # audio-bufferはSSDから読み取り専用でマウント
      - /volume1/docker/audio-recorder/data/audio-buffer:/data/audio-buffer:ro
    env_file: /volume2/docker2/birdwatch/.env
    restart: always

  webui:
    build: ./webui
    volumes:
      - /volume2/docker2/birdwatch/data:/data
    ports:
      - "5050:5050"
    restart: always
